# Generated by Django 2.0.1 on 2018-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20180319_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
    ]
