# Generated by Django 2.0.1 on 2018-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
