# Generated by Django 2.0.1 on 2018-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_venda_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
