# Generated by Django 2.0.1 on 2018-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20180310_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
