# Generated by Django 2.0.1 on 2018-04-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20180319_1533'),
        ('clientes', '0003_person_bio2'),
    ]

    operations = [
    ]
