# Generated by Django 2.0.1 on 2018-05-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20180430_2212'),
        ('clientes', '0014_merge_20180402_2033'),
    ]

    operations = [
    ]
