# Generated by Django 2.0.1 on 2018-05-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_merge_20180513_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio2',
        ),
    ]
